### ISSUE TITLE
Failed to download module with 3.2.1

### ISSUE THREAD

**Issue by byarbrough** [trussworks/terraform-aws-s3-private-bucket#194]
I was previously was using v3.2.0 of this module and Terraform 13.4.0.
Today when I tried to run `terraform init` I got this error:

```
Error: Failed to download module

Could not download module "private_bucket" (main.tf:17) source code
from
"git::https://github.com/trussworks/terraform-aws-s3-private-bucket?ref=3.2.1":
error downloading
'https://github.com/trussworks/terraform-aws-s3-private-bucket?ref=3.2.1':
/usr/bin/git exited with 1: error: pathspec '3.2.1' did not match any file(s)
known to git
```

I worked around the issue by explicitly setting the version within my module:

```terraform
module "private_bucket" {
  source                      = "trussworks/s3-private-bucket/aws"
  version                     = "3.2.0"
```

I'm not sure if this is because I tried to move already existing resources to a different version of the module or if it is something with the update to 3.2.1

**Comment by byarbrough** [comment]
@eeeady

**Comment by dynamike** [comment]
I was able to reproduce this issue with 0.13.4, but couldn't when bumping to 0.13.5. Any chance you could upgrade and try again?

**Comment by byarbrough** [comment]
Unfortunately, bumping the version requires the team to coordinate (and we ight just go right to 0.14...) No worries though! We are fine with 3.2.0 for now.

Consider specifying terraform ~> 0.13.5 in [required_version](https://github.com/trussworks/terraform-aws-s3-private-bucket/blob/v3.2.1/versions.tf#L2)?

**Comment by dynamike** [comment]
I republished under 3.2.2 and am no longer getting the errors you mentioned. Can you confirm it works now?

**Comment by byarbrough** [comment]
Good to go! Thank you
