### ISSUE TITLE
Enable Storage Class Analytics by default

### ISSUE THREAD

**Issue by ferlatte** [trussworks/terraform-aws-s3-private-bucket#2]
This:

https://docs.aws.amazon.com/AmazonS3/latest/dev/analytics-storage-class.html

If you don't have it turned on, you're gonna have a bad time later when you want to setup specialized bucket lifecycles.

**Comment by dynamike** [comment]
Moved to Pivotal -- https://www.pivotaltracker.com/story/show/169298624
