### ISSUE TITLE
Enable bucket inventory

### ISSUE THREAD

**Issue by ferlatte** [trussworks/terraform-aws-s3-private-bucket#3]
It's extremely useful to have bucket inventory, and in theory we can set it up so that it's not adding much additional cost.

Proposal: Put inventory into _AWSBucketInventory/ prefix, and enable a lifecycle policy that removes inventories older than 7 days.

Make sure you add all of the optional columns; you actually need them.

Also, consider CSV vs ORC format; ORC should be much smaller, but harder to work with unless there's already tooling that can convert it into CSV easily.

**Comment by dynamike** [comment]
Moved to Pivotal -- https://www.pivotaltracker.com/story/show/169298719
