### ISSUE TITLE
kms_master_key_id must not be null

### ISSUE THREAD

**Issue by marekaf** [trussworks/terraform-aws-s3-private-bucket#399]
Hi,

I'm using the bootstrap module but the last versions broke for me since I'm not using KMS SSE here.

The error doesn't seem to be in the bootstrap module though but rather how it passed kms_master_key_id == null into this s3 module.

```
│ Error: Invalid function argument
│
│   on .terraform/modules/bootstrap.terraform_state_bucket/main.tf line 260, in resource "aws_s3_bucket_server_side_encryption_configuration" "private_bucket":
│  260:       kms_master_key_id = length(var.kms_master_key_id) > 0 ? var.kms_master_key_id : null
│     ├────────────────
│     │ while calling length(value)
│     │ var.kms_master_key_id is null
│
│ Invalid value for "value" parameter: argument must not be null.
```

**Comment by rpdelaney** [comment]
Thanks @marekaf. I wonder why we haven't seen this problem in our own infrastructure? Anyway, if you can send a PR I'll take a look :)

**Comment by MurilloMaia** [comment]
[The default value to kms_master_key_id is ""](https://github.com/MurilloMaia/terraform-aws-s3-private-bucket/blob/main/variables.tf#LL130C19-L130C19)

[The default value to kms_master_key_id is null  on terraform-aws-bootstrap](https://github.com/trussworks/terraform-aws-bootstrap/blob/main/variables.tf#L86)

There is 2 fixes that could be addressed on this issue.

[Add a validation on aws_s3_bucket_server_side_encryption_configuration resource](https://github.com/trussworks/terraform-aws-s3-private-bucket/blob/main/main.tf#L254)

`count = var.kms_master_key_id != null ? 1 : 0`

[Change the default value to ""  on terraform-aws-bootstrap](https://github.com/trussworks/terraform-aws-bootstrap/blob/main/variables.tf#L86)

`  default     = ""`
