### ISSUE TITLE
Make logging bucket optional

### ISSUE THREAD

**Issue by brainsik** [trussworks/terraform-aws-s3-private-bucket#8]
For a greenfield AWS account where nothing has been setup yet, there is no logging bucket configured yet. This means in order to use the [terraform-aws-bootstrap](https://github.com/trussworks/terraform-aws-bootstrap) code you have to comment out the logging config from the s3 resource.

Unfortunately, how to make this optional is non-obvious since the logging config is a map and you can't use maps with conditionals in Terraform 0.11.x:

```
* module.private_bucket.aws_s3_bucket.private_bucket: At column 3, line 1: conditional operator cannot be used with map values in:

${var.logging_bucket == "" ? map() : local.logging_config}
```

Perhaps there's something more ~hacky~ clever that can be done? Or maybe we wait for Terraform 0.12 (assuming it deals with this better).

**Comment by brainsik** [comment]
Tried this tip found by @dynamike: https://github.com/terraform-providers/terraform-provider-aws/issues/2785#issuecomment-354321819

Unfortunately, I think I've hit another bug. If you include a data provider in the config (or, at least, this data provider) like:

```hcl
enabled = [{
    target_bucket = "${var.logging_bucket}"
    target_prefix = "s3/${data.aws_iam_account_alias.current.account_alias}-${var.bucket}/"
  }]
```

Then you get a bizarre error about how logging needs to be a list. But if you remove that data provider it works fine.

**Comment by brainsik** [comment]
Created terraform-providers/terraform-provider-aws#5315

**Comment by dynamike** [comment]
@brainsik Is this still needed since we are adding the logging bucket in the bootstrap module?

**Comment by dynamike** [comment]
Moved to Pivotal -- https://www.pivotaltracker.com/story/show/169347911
